services:
  api:
    container_name: personal-blog-api
    restart: always
    env_file:
      - ./.env.${NODE_ENV}
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    volumes:
      - ./:/usr/src/personal-blog-api
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    networks:
      - personal-blog-api-network
  db:
    image: postgres
    container_name: personal-blog-api-db
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - /:/data/postgres
    networks:
      - personal-blog-api-network

networks:
  personal-blog-api-network:
    driver: bridge
